blank_issues_enabled: false
contact_links:
  - name: CueScript Specification
    url: https://github.com/meikr/cuescript/blob/main/specification/v0.9/CueScript-v0.9.md
    about: Read the full specification before opening an issue
